version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: rand_names_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - rand_names

networks:
  rand_names:
    driver: bridge

volumes:
  redis_data:
